#!/usr/bin/python3
import argparse
import os
import json
import sys
from libcn.libcn import CypherNode
def main(conf):
    cn = CypherNode(cnid=conf.cnid[0], key=conf.key[0], url=conf.url[0], unsecure=conf.unsecure, verbose=conf.verbose, configfile=conf.configfile)
    resp = None
    if conf.arguments:
        resp = eval('cn.{}{}'.format(conf.command, tuple(conf.args)))
    elif not conf.arguments:
        if conf.command:
            resp = eval('cn.{}()'.format(conf.command))
    if conf.info:
        data = cn.inform(conf.info[0])
        print(data)
    if conf.list:
        cn.listing(conf.list[0])
    if conf.token:
        token = cn.get_token()
        print(token)
    if resp:
        if conf.json == True:
            print(json.dumps(resp, indent=2, sort_keys=False))
        else:
            print(json.dumps(resp))
if __name__=='__main__':
    conf = argparse.ArgumentParser()
#    config_file
    conf.add_argument('command', nargs='?', help='Command')
    conf.add_argument('arguments', nargs='*', help='Command arguments')
    conf.add_argument('--cnid', nargs=1, type=str, default=['None'], choices=['000', '001', '002', '003', None], help='Set the cyphernode ID')
    conf.add_argument('--key', nargs=1, type=str, default=['None'], help='Set the cyphernode autorisation key')
    conf.add_argument('--url', nargs=1, type=str, default=['None'], help='Set the cyphernode URL')
#    conf.add_argument('-h', '--help', help='Show this help message and exit')
    conf.add_argument('-l', '--list', nargs=1, type=str, choices=['all', 'stats', 'watcher', 'spender',' admin'], help='List command available')
    conf.add_argument('-i', '--info', nargs=1, type=str, metavar='COMMAND', help='Get command informations')
    # if configuration file exist, load it !
    if os.path.exists("{}/.cn/cn.conf".format(os.path.expanduser('~'))):
        conf.add_argument('-c', '--configfile', nargs=1, type=str, default="{}/.cn/cn.conf".format(os.path.expanduser('~')), help='Define the configuration file absolute path')
    else:
        conf.add_argument('-c', '--configfile', nargs=1, type=str, default=None, help='Define the configuration file absolute path')
    conf.add_argument('-u', '--unsecure', action="store_true", default=None, help='Ignore ssl certificate error')
    conf.add_argument('-j', '--json', action="store_true", default=None, help='Use json indentation formating')
    conf.add_argument('-t', '--token', action="store_true", default=None, help='Generate and return autorisation token')
    conf.add_argument('-v', '--verbose', action="store_true", help='Use verbose mode')
    args = conf.parse_args(sys.argv[1:])
    main(args)